const  APIEndpoints = {
    ProcedureAndPackage: {
        getServiceCategoryList: "HIMS/CMN/GetHIMSMasterDataBinding",
        getProcedureAndPackageList: "HIMS/CMN/GetBNItem",
        updateProcedureAndPackageStatus: "HIMS/CMN/StatusUpdateBNItem",
        getDiseaseList: "HIMS/CMN/GetHIMSMasterDataBinding",
        addProcedureAndPackage: "HIMS/CMN/SaveBNItem",
        getItemGroupList: "Setup/IMM/GetInventoryMasterBinding",
        getItemMasterList: "Setup/IMM/GetInventoryBNItemNo",
      },
      OPDVisit: {
        GetHIMSMasterDataBinding: "HIMS/CMN/GetHIMSMasterDataBinding",
        GetMasterDataBinding: "Setup/Common/GetMasterDataBinding",
        GetHRMSMasterData: "HRMS/GetHRMSMasterDataBinding",
        GetPatientAppointment: "HIMS/Appointment/GetPatientAppointment",
        GetOpdVistList: "HIMS/OPD/GetPatientVisit",
        GetMasterDataFile: "HIMS/CMN/GetMasterDataFile",
        AddOpdPatientVisitData: "HIMS/OPD/AddPatientVisit",
        AddPatientInformation: "HIMS/Appointment/AddPatient",
        GetPatientsList: "HIMS/OPD/GetPatientList",
        GetTotalAppointment: "HIMS/Appointment/PatientAppointmentVisitCount",
        CancelAppointments: "HIMS/Appointment/RemovePatientAppointment",
      },
      PatientAppointment: {
        GetPatientAppointment: "HIMS/Appointment/GetPatientAppointment",
        GetPatientAppointmentView: "HIMS/Appointment/GetPatientAppointmentView",
        GetHIMSMasterDataBinding: "HIMS/CMN/GetHIMSMasterDataBinding",
        AssignCommonRelationManage: "Setup/Common/AssignCommonRelationManage",
        GetMasterDataFile: "HIMS/CMN/GetMasterDataFile",
        GetPatientList: "HIMS/CMN/GetPatient",
        SaveAppointment: "HIMS/Appointment/AddPatientAppointment",
        GetAppointmentSlotList: "HIMS/Appointment/GetAppointmentSlot",
        GetPatientViewSpeciality: "HIMS/CMN/GetHIMSMasterDataBinding",
        OnDeleteAppointment: "HIMS/Appointment/PatientAppointmentDelete",
        GetPatientSearchView: "HIMS/Appointment/PatientAppointmentView",
        GetHospitalRooms: "HIMS/CMN/GetHIMSMasterDataBinding",
        ReScheduleAppointment: "HIMS/Appointment/PatientAppointmentReSchedule",
        AddPatientInformation: "HIMS/Appointment/AddPatient",
        GetPatientsList: "HIMS/OPD/GetPatientList",
        GetPatientAppointmentSummary: "HIMS/Appointment/GetPatientAppointmentSummary",
        GetPatientAppointmentHistory: "HIMS/Appointment/GetPatientAppointmentHistory",
        SendSMSToDest: "HIMS/CMN/SendSMSToDest",
        GetPatientAppointmentList: "HIMS/Appointment/GetPatientAppointmentList",
        ValidateWhatsAppContact: "HIMS/CMN/ValidateWhatsAppContact",
        SendSMSToDestination: "HIMS/CMN/SendSMSToDestination",
        GetDoctorScheduleSummary: "HIMS/Appointment/GetDoctorScheduleSummary",
      },
      Configuration: {
        GetMasterPage: "Setup/BIZNEXT/GetMasterPage",
        GetPageConfig: "Setup/BIZNEXT/GetPageConfig",
        UpdateBiznextPage: "Setup/BIZNEXT/UpdateBiznextPage",
        AddMasterExtensionConfig: "Setup/BIZNEXT/AddMasterExtensionConfig",
        GetMasterExtensionConfig: "Setup/BIZNEXT/GetMasterExtensionConfig",
        UpdateMasterExtensionConfig: "Setup/BIZNEXT/UpdateMasterExtensionConfig",
        UpdateMasterExtensionLogicQuery: "Setup/BIZNEXT/UpdateMasterExtensionLogicQuery",
        PageConfigPublish: "Setup/BIZNEXT/PageConfigPublish",
        GetExtensionValue: "Setup/BIZNEXT/GetExtensionValue",
        PublishExtensionField: "Setup/BIZNEXT/ReleaseExtensionField",
        GetMasterDataBinding: "Setup/Common/GetMasterDataBinding",
      },
}
export default APIEndpoints;